use std::str::FromStr;

#[allow(non_camel_case_types)]
#[allow(dead_code)]
#[derive(Debug, Clone)]
pub enum Nacionalidad {
    AD_Andorra,
    AE_UnitedArabEmirates,
    AF_Afghanistan,
    AG_Antigua_Barbuda,
    AI_Anguilla,
    AL_Albania,
    AM_Armenia,
    AO_Angola,
    AQ_Antarctica,
    AR_Argentina,
    AS_American,
    AT_Austria,
    AU_Australia,
    AW_Aruba,
    AX_ÅlandIslands,
    AZ_Azerbaijan,
    BA_Bosnia_Herzegovina,
    BB_Barbados,
    BD_Bangladesh,
    BE_Belgium,
    BF_Burkina_Faso,
    BG_Bulgaria,
    BH_Bahrain,
    BI_Burundi,
    BJ_Benin,
    BL_Saint_Barthélemy,
    BM_Bermuda,
    BN_Brunei_Darussalam,
    BO_Bolivia,
    BQ_Bonaire_SintEustatius_Saba,
    BR_Brazil,
    BS_Bahamas,
    BT_Bhutan,
    BV_BouvetIsland,
    BW_Botswana,
    BY_Belarus,
    BZ_Belize,
    CA_Canada,
    CC_CocosIslands,
    CD_Congo,
    CF_CentralAfricanRepublic,
    CG_Congo,
    CH_Switzerland,
    CI_CôteIvoire,
    CK_CookIslands,
    CL_Chile,
    CM_Cameroon,
    CN_China,
    CO_Colombia,
    CR_CostaRica,
    CU_Cuba,
    CV_CaboVerde,
    CW_Curaçao,
    CX_ChristmasIsland,
    CY_Cyprus,
    CZ_Czechia,
    DE_Germany,
    DJ_Djibouti,
    DK_Denmark,
    DM_Dominica,
    DO_DominicanRepublic,
    DZ_Algeria,
    EC_Ecuador,
    EE_Estonia,
    EG_Egypt,
    EH_WesternSahara,
    ER_Eritrea,
    ES_Spain,
    ET_Ethiopia,
    FI_Finland,
    FJ_Fiji,
    FK_FalklandIslands,
    FM_Micronesia,
    FO_FaroeIslands,
    FR_France,
    GA_Gabon,
    GB_UnitedKingdom,
    GD_Grenada,
    GE_Georgia,
    GF_FrenchGuiana,
    GG_Guernsey,
    GH_Ghana,
    GI_Gibraltar,
    GL_Greenland,
    GM_Gambia,
    GN_Guinea,
    GP_Guadeloupe,
    GQ_EquatorialGuinea,
    GR_Greece,
    GS_SouthGeorgiaSouthSandwichIslands,
    GT_Guatemala,
    GU_Guam,
    GW_Guinea_Bissau,
    GY_Guyana,
    HK_HongKong,
    HM_HeardMcDonaldIslands,
    HN_Honduras,
    HR_Croatia,
    HT_Haiti,
    HU_Hungary,
    ID_Indonesia,
    IE_Ireland,
    IL_Israel,
    IN_India,
    IQ_Iraq,
    IR_Iran,
    IS_Iceland,
    IT_Italy,
    JE_Jersey,
    JM_Jamaica,
    JO_Jordan,
    JP_Japan,
    KE_Kenya,
    KG_Kyrgyzstan,
    KH_Cambodia,
    KI_Kiribati,
    KM_Comoros,
    KN_SaintKitts_Nevis,
    KP_KoreaNorth,
    KR_KoreaSouth,
    KW_Kuwait,
    KY_CaymanIslands,
    KZ_Kazakhstan,
    LA_Laos,
    LB_Lebanon,
    LC_SaintLucia,
    LI_Liechtenstein,
    LK_SriLanka,
    LR_Liberia,
    LS_Lesotho,
    LT_Lithuania,
    LU_Luxembourg,
    LV_Latvia,
    LY_Libya,
    MA_Morocco,
    MC_Monaco,
    MD_Moldova,
    ME_Montenegro,
    MG_Madagascar,
    MH_MarshallIslands,
    MK_MacedoniaNorth,
    ML_Mali,
    MM_Myanmar,
    MN_Mongolia,
    MO_Macao,
    MP_NorthernMarianaIslands,
    MQ_Martinique,
    MR_Mauritania,
    MS_Montserrat,
    MT_Malta,
    MU_Mauritius,
    MV_Maldives,
    MW_Malawi,
    MX_Mexico,
    MY_Malaysia,
    MZ_Mozambique,
    NA_Namibia,
    NC_NewCaledonia,
    NE_Niger,
    NF_NorfolkIsland,
    NG_Nigeria,
    NI_Nicaragua,
    NL_Netherlands,
    NO_Norway,
    NP_Nepal,
    NR_Nauru,
    NU_Niue,
    NZ_NewZealand,
    OM_Oman,
    PA_Panama,
    PE_Peru,
    PF_FrenchPolynesia,
    PG_PapuaNewGuinea,
    PH_Philippines,
    PK_Pakistan,
    PL_Poland,
    PM_SaintPierre_Miquelon,
    PN_PitcairnIslands,
    PR_PuertoRico,
    PS_Palestine,
    PT_Portugal,
    PW_Palau,
    PY_Paraguay,
    QA_Qatar,
    RE_Reunion,
    RO_Romania,
    RS_Serbia,
    RU_RussianFederation,
    RW_Rwanda,
    SA_SaudiArabia,
    SB_SolomonIslands,
    SC_Seychelles,
    SD_Sudan,
    SE_Sweden,
    SG_Singapore,
    SH_SaintHelena_Ascension_TristanCunha,
    SI_Slovenia,
    SJ_Svalbard_JanMayen,
    SK_Slovakia,
    SL_SierraLeone,
    SM_SanMarino,
    SN_Senegal,
    SO_Somalia,
    SR_Suriname,
    SS_SouthSudan,
    ST_SaoTomePrincipe,
    SV_ElSalvador,
    SY_Syria,
    SZ_Eswatini,
    TC_TurksCaicosIslands,
    TD_Chad,
    TG_Togo,
    TH_Thailand,
    TJ_Tajikistan,
    TK_TokelauIslands,
    TL_Timor_Leste,
    TM_Turkmenistan,
    TN_Tunisia,
    TO_Tonga,
    TR_Türkiye,
    TT_Trinidad_Tobago,
    TV_Tuvalu,
    TW_Taiwan,
    TZ_Tanzania,
    UA_Ukraine,
    UG_Uganda,
    US_UnitedStatesOfAmerica,
    UY_Uruguay,
    UZ_Uzbekistan,
    VA_HolySee,
    VC_SaintVincent_Grenadines,
    VE_Venezuela,
    VG_VirginIslandsBrit,
    VI_VirginIslandsUS,
    VN_VietNam,
    VU_Vanuatu,
    WF_Wallis_Futuna,
    WS_Samoa,
    YE_Yemen,
    YT_Mayotte,
    ZA_SouthAfrica,
    ZM_Zambia,
    ZW_Zimbabwe,
}

impl std::fmt::Display for Nacionalidad {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "{:?}", self)
    }
}

impl FromStr for Nacionalidad {
    type Err = String;

    fn from_str(s: &str) -> Result<Self, Self::Err> {
        match s {
            "AD_Andorra" => Ok(Nacionalidad::AD_Andorra),
            "AE_UnitedArabEmirates" => Ok(Nacionalidad::AE_UnitedArabEmirates),
            "AF_Afghanistan" => Ok(Nacionalidad::AF_Afghanistan),
            "AG_Antigua_Barbuda" => Ok(Nacionalidad::AG_Antigua_Barbuda),
            "AI_Anguilla" => Ok(Nacionalidad::AI_Anguilla),
            "AL_Albania" => Ok(Nacionalidad::AL_Albania),
            "AM_Armenia" => Ok(Nacionalidad::AM_Armenia),
            "AO_Angola" => Ok(Nacionalidad::AO_Angola),
            "AQ_Antarctica" => Ok(Nacionalidad::AQ_Antarctica),
            "AR_Argentina" => Ok(Nacionalidad::AR_Argentina),
            "AS_American" => Ok(Nacionalidad::AS_American),
            "AT_Austria" => Ok(Nacionalidad::AT_Austria),
            "AU_Australia" => Ok(Nacionalidad::AU_Australia),
            "AW_Aruba" => Ok(Nacionalidad::AW_Aruba),
            "AX_ÅlandIslands" => Ok(Nacionalidad::AX_ÅlandIslands),
            "AZ_Azerbaijan" => Ok(Nacionalidad::AZ_Azerbaijan),
            "BA_Bosnia_Herzegovina" => Ok(Nacionalidad::BA_Bosnia_Herzegovina),
            "BB_Barbados" => Ok(Nacionalidad::BB_Barbados),
            "BD_Bangladesh" => Ok(Nacionalidad::BD_Bangladesh),
            "BE_Belgium" => Ok(Nacionalidad::BE_Belgium),
            "BF_Burkina_Faso" => Ok(Nacionalidad::BF_Burkina_Faso),
            "BG_Bulgaria" => Ok(Nacionalidad::BG_Bulgaria),
            "BH_Bahrain" => Ok(Nacionalidad::BH_Bahrain),
            "BI_Burundi" => Ok(Nacionalidad::BI_Burundi),
            "BJ_Benin" => Ok(Nacionalidad::BJ_Benin),
            "BL_Saint_Barthélemy" => Ok(Nacionalidad::BL_Saint_Barthélemy),
            "BM_Bermuda" => Ok(Nacionalidad::BM_Bermuda),
            "BN_Brunei_Darussalam" => Ok(Nacionalidad::BN_Brunei_Darussalam),
            "BO_Bolivia" => Ok(Nacionalidad::BO_Bolivia),
            "BQ_Bonaire_SintEustatius_Saba" => Ok(Nacionalidad::BQ_Bonaire_SintEustatius_Saba),
            "BR_Brazil" => Ok(Nacionalidad::BR_Brazil),
            "BS_Bahamas" => Ok(Nacionalidad::BS_Bahamas),
            "BT_Bhutan" => Ok(Nacionalidad::BT_Bhutan),
            "BV_BouvetIsland" => Ok(Nacionalidad::BV_BouvetIsland),
            "BW_Botswana" => Ok(Nacionalidad::BW_Botswana),
            "BY_Belarus" => Ok(Nacionalidad::BY_Belarus),
            "BZ_Belize" => Ok(Nacionalidad::BZ_Belize),
            "CA_Canada" => Ok(Nacionalidad::CA_Canada),
            "CC_CocosIslands" => Ok(Nacionalidad::CC_CocosIslands),
            "CD_Congo" => Ok(Nacionalidad::CD_Congo),
            "CF_CentralAfricanRepublic" => Ok(Nacionalidad::CF_CentralAfricanRepublic),
            "CG_Congo" => Ok(Nacionalidad::CG_Congo),
            "CH_Switzerland" => Ok(Nacionalidad::CH_Switzerland),
            "CI_CôteIvoire" => Ok(Nacionalidad::CI_CôteIvoire),
            "CK_CookIslands" => Ok(Nacionalidad::CK_CookIslands),
            "CL_Chile" => Ok(Nacionalidad::CL_Chile),
            "CM_Cameroon" => Ok(Nacionalidad::CM_Cameroon),
            "CN_China" => Ok(Nacionalidad::CN_China),
            "CO_Colombia" => Ok(Nacionalidad::CO_Colombia),
            "CR_CostaRica" => Ok(Nacionalidad::CR_CostaRica),
            "CU_Cuba" => Ok(Nacionalidad::CU_Cuba),
            "CV_CaboVerde" => Ok(Nacionalidad::CV_CaboVerde),
            "CW_Curaçao" => Ok(Nacionalidad::CW_Curaçao),
            "CX_ChristmasIsland" => Ok(Nacionalidad::CX_ChristmasIsland),
            "CY_Cyprus" => Ok(Nacionalidad::CY_Cyprus),
            "CZ_Czechia" => Ok(Nacionalidad::CZ_Czechia),
            "DE_Germany" => Ok(Nacionalidad::DE_Germany),
            "DJ_Djibouti" => Ok(Nacionalidad::DJ_Djibouti),
            "DK_Denmark" => Ok(Nacionalidad::DK_Denmark),
            "DM_Dominica" => Ok(Nacionalidad::DM_Dominica),
            "DO_DominicanRepublic" => Ok(Nacionalidad::DO_DominicanRepublic),
            "DZ_Algeria" => Ok(Nacionalidad::DZ_Algeria),
            "EC_Ecuador" => Ok(Nacionalidad::EC_Ecuador),
            "EE_Estonia" => Ok(Nacionalidad::EE_Estonia),
            "EG_Egypt" => Ok(Nacionalidad::EG_Egypt),
            "EH_WesternSahara" => Ok(Nacionalidad::EH_WesternSahara),
            "ER_Eritrea" => Ok(Nacionalidad::ER_Eritrea),
            "ES_Spain" => Ok(Nacionalidad::ES_Spain),
            "ET_Ethiopia" => Ok(Nacionalidad::ET_Ethiopia),
            "FI_Finland" => Ok(Nacionalidad::FI_Finland),
            "FJ_Fiji" => Ok(Nacionalidad::FJ_Fiji),
            "FK_FalklandIslands" => Ok(Nacionalidad::FK_FalklandIslands),
            "FM_Micronesia" => Ok(Nacionalidad::FM_Micronesia),
            "FO_FaroeIslands" => Ok(Nacionalidad::FO_FaroeIslands),
            "FR_France" => Ok(Nacionalidad::FR_France),
            "GA_Gabon" => Ok(Nacionalidad::GA_Gabon),
            "GB_UnitedKingdom" => Ok(Nacionalidad::GB_UnitedKingdom),
            "GD_Grenada" => Ok(Nacionalidad::GD_Grenada),
            "GE_Georgia" => Ok(Nacionalidad::GE_Georgia),
            "GF_FrenchGuiana" => Ok(Nacionalidad::GF_FrenchGuiana),
            "GG_Guernsey" => Ok(Nacionalidad::GG_Guernsey),
            "GH_Ghana" => Ok(Nacionalidad::GH_Ghana),
            "GI_Gibraltar" => Ok(Nacionalidad::GI_Gibraltar),
            "GL_Greenland" => Ok(Nacionalidad::GL_Greenland),
            "GM_Gambia" => Ok(Nacionalidad::GM_Gambia),
            "GN_Guinea" => Ok(Nacionalidad::GN_Guinea),
            "GP_Guadeloupe" => Ok(Nacionalidad::GP_Guadeloupe),
            "GQ_EquatorialGuinea" => Ok(Nacionalidad::GQ_EquatorialGuinea),
            "GR_Greece" => Ok(Nacionalidad::GR_Greece),
            "GS_SouthGeorgiaSouthSandwichIslands" => {
                Ok(Nacionalidad::GS_SouthGeorgiaSouthSandwichIslands)
            }
            "GT_Guatemala" => Ok(Nacionalidad::GT_Guatemala),
            "GU_Guam" => Ok(Nacionalidad::GU_Guam),
            "GW_Guinea_Bissau" => Ok(Nacionalidad::GW_Guinea_Bissau),
            "GY_Guyana" => Ok(Nacionalidad::GY_Guyana),
            "HK_HongKong" => Ok(Nacionalidad::HK_HongKong),
            "HM_HeardMcDonaldIslands" => Ok(Nacionalidad::HM_HeardMcDonaldIslands),
            "HN_Honduras" => Ok(Nacionalidad::HN_Honduras),
            "HR_Croatia" => Ok(Nacionalidad::HR_Croatia),
            "HT_Haiti" => Ok(Nacionalidad::HT_Haiti),
            "HU_Hungary" => Ok(Nacionalidad::HU_Hungary),
            "ID_Indonesia" => Ok(Nacionalidad::ID_Indonesia),
            "IE_Ireland" => Ok(Nacionalidad::IE_Ireland),
            "IL_Israel" => Ok(Nacionalidad::IL_Israel),
            "IN_India" => Ok(Nacionalidad::IN_India),
            "IQ_Iraq" => Ok(Nacionalidad::IQ_Iraq),
            "IR_Iran" => Ok(Nacionalidad::IR_Iran),
            "IS_Iceland" => Ok(Nacionalidad::IS_Iceland),
            "IT_Italy" => Ok(Nacionalidad::IT_Italy),
            "JE_Jersey" => Ok(Nacionalidad::JE_Jersey),
            "JM_Jamaica" => Ok(Nacionalidad::JM_Jamaica),
            "JO_Jordan" => Ok(Nacionalidad::JO_Jordan),
            "JP_Japan" => Ok(Nacionalidad::JP_Japan),
            "KE_Kenya" => Ok(Nacionalidad::KE_Kenya),
            "KG_Kyrgyzstan" => Ok(Nacionalidad::KG_Kyrgyzstan),
            "KH_Cambodia" => Ok(Nacionalidad::KH_Cambodia),
            "KI_Kiribati" => Ok(Nacionalidad::KI_Kiribati),
            "KM_Comoros" => Ok(Nacionalidad::KM_Comoros),
            "KN_SaintKitts_Nevis" => Ok(Nacionalidad::KN_SaintKitts_Nevis),
            "KP_KoreaNorth" => Ok(Nacionalidad::KP_KoreaNorth),
            "KR_KoreaSouth" => Ok(Nacionalidad::KR_KoreaSouth),
            "KW_Kuwait" => Ok(Nacionalidad::KW_Kuwait),
            "KY_CaymanIslands" => Ok(Nacionalidad::KY_CaymanIslands),
            "KZ_Kazakhstan" => Ok(Nacionalidad::KZ_Kazakhstan),
            "LA_Laos" => Ok(Nacionalidad::LA_Laos),
            "LB_Lebanon" => Ok(Nacionalidad::LB_Lebanon),
            "LC_SaintLucia" => Ok(Nacionalidad::LC_SaintLucia),
            "LI_Liechtenstein" => Ok(Nacionalidad::LI_Liechtenstein),
            "LK_SriLanka" => Ok(Nacionalidad::LK_SriLanka),
            "LR_Liberia" => Ok(Nacionalidad::LR_Liberia),
            "LS_Lesotho" => Ok(Nacionalidad::LS_Lesotho),
            "LT_Lithuania" => Ok(Nacionalidad::LT_Lithuania),
            "LU_Luxembourg" => Ok(Nacionalidad::LU_Luxembourg),
            "LV_Latvia" => Ok(Nacionalidad::LV_Latvia),
            "LY_Libya" => Ok(Nacionalidad::LY_Libya),
            "MA_Morocco" => Ok(Nacionalidad::MA_Morocco),
            "MC_Monaco" => Ok(Nacionalidad::MC_Monaco),
            "MD_Moldova" => Ok(Nacionalidad::MD_Moldova),
            "ME_Montenegro" => Ok(Nacionalidad::ME_Montenegro),
            "MG_Madagascar" => Ok(Nacionalidad::MG_Madagascar),
            "MH_MarshallIslands" => Ok(Nacionalidad::MH_MarshallIslands),
            "MK_MacedoniaNorth" => Ok(Nacionalidad::MK_MacedoniaNorth),
            "ML_Mali" => Ok(Nacionalidad::ML_Mali),
            "MM_Myanmar" => Ok(Nacionalidad::MM_Myanmar),
            "MN_Mongolia" => Ok(Nacionalidad::MN_Mongolia),
            "MO_Macao" => Ok(Nacionalidad::MO_Macao),
            "MP_NorthernMarianaIslands" => Ok(Nacionalidad::MP_NorthernMarianaIslands),
            "MQ_Martinique" => Ok(Nacionalidad::MQ_Martinique),
            "MR_Mauritania" => Ok(Nacionalidad::MR_Mauritania),
            "MS_Montserrat" => Ok(Nacionalidad::MS_Montserrat),
            "MT_Malta" => Ok(Nacionalidad::MT_Malta),
            "MU_Mauritius" => Ok(Nacionalidad::MU_Mauritius),
            "MV_Maldives" => Ok(Nacionalidad::MV_Maldives),
            "MW_Malawi" => Ok(Nacionalidad::MW_Malawi),
            "MX_Mexico" => Ok(Nacionalidad::MX_Mexico),
            "MY_Malaysia" => Ok(Nacionalidad::MY_Malaysia),
            "MZ_Mozambique" => Ok(Nacionalidad::MZ_Mozambique),
            "NA_Namibia" => Ok(Nacionalidad::NA_Namibia),
            "NC_NewCaledonia" => Ok(Nacionalidad::NC_NewCaledonia),
            "NE_Niger" => Ok(Nacionalidad::NE_Niger),
            "NF_NorfolkIsland" => Ok(Nacionalidad::NF_NorfolkIsland),
            "NG_Nigeria" => Ok(Nacionalidad::NG_Nigeria),
            "NI_Nicaragua" => Ok(Nacionalidad::NI_Nicaragua),
            "NL_Netherlands" => Ok(Nacionalidad::NL_Netherlands),
            "NO_Norway" => Ok(Nacionalidad::NO_Norway),
            "NP_Nepal" => Ok(Nacionalidad::NP_Nepal),
            "NR_Nauru" => Ok(Nacionalidad::NR_Nauru),
            "NU_Niue" => Ok(Nacionalidad::NU_Niue),
            "NZ_NewZealand" => Ok(Nacionalidad::NZ_NewZealand),
            "OM_Oman" => Ok(Nacionalidad::OM_Oman),
            "PA_Panama" => Ok(Nacionalidad::PA_Panama),
            "PE_Peru" => Ok(Nacionalidad::PE_Peru),
            "PF_FrenchPolynesia" => Ok(Nacionalidad::PF_FrenchPolynesia),
            "PG_PapuaNewGuinea" => Ok(Nacionalidad::PG_PapuaNewGuinea),
            "PH_Philippines" => Ok(Nacionalidad::PH_Philippines),
            "PK_Pakistan" => Ok(Nacionalidad::PK_Pakistan),
            "PL_Poland" => Ok(Nacionalidad::PL_Poland),
            "PM_SaintPierre_Miquelon" => Ok(Nacionalidad::PM_SaintPierre_Miquelon),
            "PN_PitcairnIslands" => Ok(Nacionalidad::PN_PitcairnIslands),
            "PR_PuertoRico" => Ok(Nacionalidad::PR_PuertoRico),
            "PS_Palestine" => Ok(Nacionalidad::PS_Palestine),
            "PT_Portugal" => Ok(Nacionalidad::PT_Portugal),
            "PW_Palau" => Ok(Nacionalidad::PW_Palau),
            "PY_Paraguay" => Ok(Nacionalidad::PY_Paraguay),
            "QA_Qatar" => Ok(Nacionalidad::QA_Qatar),
            "RE_Reunion" => Ok(Nacionalidad::RE_Reunion),
            "RO_Romania" => Ok(Nacionalidad::RO_Romania),
            "RS_Serbia" => Ok(Nacionalidad::RS_Serbia),
            "RU_RussianFederation" => Ok(Nacionalidad::RU_RussianFederation),
            "RW_Rwanda" => Ok(Nacionalidad::RW_Rwanda),
            "SA_SaudiArabia" => Ok(Nacionalidad::SA_SaudiArabia),
            "SB_SolomonIslands" => Ok(Nacionalidad::SB_SolomonIslands),
            "SC_Seychelles" => Ok(Nacionalidad::SC_Seychelles),
            "SD_Sudan" => Ok(Nacionalidad::SD_Sudan),
            "SE_Sweden" => Ok(Nacionalidad::SE_Sweden),
            "SG_Singapore" => Ok(Nacionalidad::SG_Singapore),
            "SH_SaintHelena_Ascension_TristanCunha" => {
                Ok(Nacionalidad::SH_SaintHelena_Ascension_TristanCunha)
            }
            "SI_Slovenia" => Ok(Nacionalidad::SI_Slovenia),
            "SJ_Svalbard_JanMayen" => Ok(Nacionalidad::SJ_Svalbard_JanMayen),
            "SK_Slovakia" => Ok(Nacionalidad::SK_Slovakia),
            "SL_SierraLeone" => Ok(Nacionalidad::SL_SierraLeone),
            "SM_SanMarino" => Ok(Nacionalidad::SM_SanMarino),
            "SN_Senegal" => Ok(Nacionalidad::SN_Senegal),
            "SO_Somalia" => Ok(Nacionalidad::SO_Somalia),
            "SR_Suriname" => Ok(Nacionalidad::SR_Suriname),
            "SS_SouthSudan" => Ok(Nacionalidad::SS_SouthSudan),
            "ST_SaoTomePrincipe" => Ok(Nacionalidad::ST_SaoTomePrincipe),
            "SV_ElSalvador" => Ok(Nacionalidad::SV_ElSalvador),
            "SY_Syria" => Ok(Nacionalidad::SY_Syria),
            "SZ_Eswatini" => Ok(Nacionalidad::SZ_Eswatini),
            "TC_TurksCaicosIslands" => Ok(Nacionalidad::TC_TurksCaicosIslands),
            "TD_Chad" => Ok(Nacionalidad::TD_Chad),
            "TG_Togo" => Ok(Nacionalidad::TG_Togo),
            "TH_Thailand" => Ok(Nacionalidad::TH_Thailand),
            "TJ_Tajikistan" => Ok(Nacionalidad::TJ_Tajikistan),
            "TK_TokelauIslands" => Ok(Nacionalidad::TK_TokelauIslands),
            "TL_Timor_Leste" => Ok(Nacionalidad::TL_Timor_Leste),
            "TM_Turkmenistan" => Ok(Nacionalidad::TM_Turkmenistan),
            "TN_Tunisia" => Ok(Nacionalidad::TN_Tunisia),
            "TO_Tonga" => Ok(Nacionalidad::TO_Tonga),
            "TR_Türkiye" => Ok(Nacionalidad::TR_Türkiye),
            "TT_Trinidad_Tobago" => Ok(Nacionalidad::TT_Trinidad_Tobago),
            "TV_Tuvalu" => Ok(Nacionalidad::TV_Tuvalu),
            "TW_Taiwan" => Ok(Nacionalidad::TW_Taiwan),
            "TZ_Tanzania" => Ok(Nacionalidad::TZ_Tanzania),
            "UA_Ukraine" => Ok(Nacionalidad::UA_Ukraine),
            "UG_Uganda" => Ok(Nacionalidad::UG_Uganda),
            "US_UnitedStatesOfAmerica" => Ok(Nacionalidad::US_UnitedStatesOfAmerica),
            "UY_Uruguay" => Ok(Nacionalidad::UY_Uruguay),
            "UZ_Uzbekistan" => Ok(Nacionalidad::UZ_Uzbekistan),
            "VA_HolySee" => Ok(Nacionalidad::VA_HolySee),
            "VC_SaintVincent_Grenadines" => Ok(Nacionalidad::VC_SaintVincent_Grenadines),
            "VE_Venezuela" => Ok(Nacionalidad::VE_Venezuela),
            "VG_VirginIslandsBrit" => Ok(Nacionalidad::VG_VirginIslandsBrit),
            "VI_VirginIslandsUS" => Ok(Nacionalidad::VI_VirginIslandsUS),
            "VN_VietNam" => Ok(Nacionalidad::VN_VietNam),
            "VU_Vanuatu" => Ok(Nacionalidad::VU_Vanuatu),
            "WF_Wallis_Futuna" => Ok(Nacionalidad::WF_Wallis_Futuna),
            "WS_Samoa" => Ok(Nacionalidad::WS_Samoa),
            "YE_Yemen" => Ok(Nacionalidad::YE_Yemen),
            "YT_Mayotte" => Ok(Nacionalidad::YT_Mayotte),
            "ZA_SouthAfrica" => Ok(Nacionalidad::ZA_SouthAfrica),
            "ZM_Zambia" => Ok(Nacionalidad::ZM_Zambia),
            "ZW_Zimbabwe" => Ok(Nacionalidad::ZW_Zimbabwe),
            _ => Err(format!(
                "[{s}] no está en la lista de nacionalidades del programa."
            )),
        }
    }
}
